### ISSUE TITLE
Corruption/artifacts?

### ISSUE THREAD

**Issue by brianreavis** [mapnik/node-mapnik#445]
I'm not sure what's going on here, but we've been noticing mapnik outputting some strange artifacts. The problem is intermittent – a re-render of the same area makes it go away. The node-mapnik version is the latest one: 3.3.0. Any ideas? Other notes:
- This is with tilelive-mapnik
- It seems to have to do with rendering of rasters (the artifact color matches our hillshade color)
- PNG output

![corruption](https://cloud.githubusercontent.com/assets/118480/7713944/461d47b0-fe38-11e4-9759-0d27898fab4a.png)
4x4 metatile (the cyan lines are the tile boundaries)

**Comment by springmeyer** [comment]
Thanks for the details. We've not yet tagged a new node-mapnik since #433 was fixed, so it might be that. Also, to clarify: is the blue box the artifact or is that just the browser highlight (the the artifacts are the faint semi-transparent blue bands on the top 1/3 of those tiles)?

**Comment by brianreavis** [comment]
@springmeyer The blue box is the browser highlight – sorry for not clarifying! The artifact is the pixel'y blue band at the top 1/3.

**Comment by springmeyer** [comment]
Okay, thanks. I worry this is the same issue as #437. Are you seeing any logs like https://github.com/mapnik/node-mapnik/issues/437#issuecomment-101592842 at the same times as you see these artifacts?

**Comment by springmeyer** [comment]
> Are you seeing any logs like #437 (comment) at the same times as you see these artifacts?

bump @brianreavis ^^

**Comment by brianreavis** [comment]
I think we can hold off on this until #437 is fixed, I think. I unfortunately haven't watched the logs closely enough to tell if they happen at the same time. This one's a bugger. I'll keep this thread updated with any more information I can find.

You're probably right – there's a good chance that it's correlated to (or the same as) the other issue. We can close / re-open if necessary to cut down on Issue noise if you'd like

**Comment by springmeyer** [comment]
okay, thanks. I'm happy to keep open. I'm headed on vacation next week so trying to tie together ideas as much as possible. Hopefully when I'm back the solution will be clear :) At the least hope to have time to replicate.

**Comment by brianreavis** [comment]
Haha, sounds great. Enjoy the vacation!

**Comment by springmeyer** [comment]
@brianreavis - Lots of action over at #437. Yesterday @mojodna and I worked to run his testcase against node-mapnik master + mapnik master + gdal 2.0.0 on OS X. My summary is:

  - @mojodna has not been seeing image corruption, mainly TIFF errors and occasional crashes.
  - It is looking like using GDAL 2.0.0 fixes his problem overall
  - So, I'm starting to wonder again if your problem (corrupted images) might be different 

Next actions I see here are:

 - I'll create some alternative node-mapnik binaries against mapnik master + gdal master
 - @brianreavis sees if the bug still replicates with those binaries
 - If that fixes this problem then we sync up about moving on https://github.com/naturalatlas/node-gdal/issues/110 so that the next release of node-mapnik and node-gdal could both use the same version.

Sound good?

/cc @brandonreavis

**Comment by brianreavis** [comment]
Sounds awesome. You guys and @mojodna have been killing it over there. It's been hard to keep up! Let me know what to try out and I'll give it a whirl.

**Comment by springmeyer** [comment]
@brianreavis - okay, you can give the binaries a spin like:

```json
"mapnik": "https://github.com/mapnik/node-mapnik/tarball/gdal2",
```

And set `export VRT_SHARED_SOURCE=0`

The binaries will be available once https://travis-ci.org/mapnik/node-mapnik/builds/69403464 is all green.

**Comment by brianreavis** [comment]
Perfect. Just put that in place! I'll watch the logs for #437 and keep an eye out for any new instances of the artifacts.

**Comment by springmeyer** [comment]
Thank you. Hoping for the best.

**Comment by springmeyer** [comment]
closing this as it sounds like the 2.0 update resolved! https://github.com/mapnik/node-mapnik/issues/437#issuecomment-118929702
