### ISSUE TITLE
Configure ignores CXX environment variable

### ISSUE THREAD

**Issue by pnorman** [mapnik/node-mapnik#452]
```
export CXX=clang++35
./configure
```
gives the error
```
Checking if compiler (g++) supports -std=c++11 flag... (cached) no
C++ compiler does not support C++11 standard (-std=c++11), which is required. Please upgrade your compiler to at least g++ 4.7 (ideally 4.8)
```

Inspecting config.log reveals it is trying the command `g++ -o .sconf_temp/conftest_2.o -c -std=c++11 -DSHAPE_MEMORY_MAPPED_FILE -Iinclude -I/usr/include -I/usr/local/include/freetype2 -I/usr/local/include/libxml2 .sconf_temp/conftest_2.cpp`

**Comment by springmeyer** [comment]
node-mapnik does not have a `./configure` script so I presume you intended to create this at the mapnik repo? Either way, this behavior is by design. The `./configure` script is a shim around scons and the longstanding behavior of the scons script is to only accept options via argument and not by environment.

**Comment by pnorman** [comment]
> you intended to create this at the mapnik repo?

yes
