### ISSUE TITLE
SVG rendering - SVG to PNG

### ISSUE THREAD

**Issue by tmcw** [mapnik/node-mapnik#466]
I would like to achieve the equivalent of https://github.com/mapnik/mapnik/blob/master/utils/svg2png/svg2png.cpp except through node-mapnik bindings, with the intent of

> Given a collection of SVG images, quickly rasterize them and compose them into a sprite consumable by Mapbox GL JS and Mapbox GL Native

This API would look like

```js
mapnik.rasterize(svgBuffer, { scale: 2 }, function(err, res) {
  // res is a png buffer
});
```

Or similarly - instead of taking a buffer, it could take a file path, or instead of being async, it could be sync.

/cc @springmeyer @danpat @flippmoke

**Comment by springmeyer** [comment]
Sounds good to expose this @tmcw. As per chat I like `mapnik.Image.fromSVG` naming more, but I think the best thing would be to start coding a prototype and see how it feels.

Other thoughts:

  - We'll need to pay attention to pixel snapping per https://github.com/mapnik/mapnik/issues/1316 and its interplay with sprite layout
  - Sprites can likely be created via `mapnik.Image.composite` which accepts dx/dy arguments to add a sub image into the larger image. E.g. we used this API to create side-by-side images in python-mapnik: https://github.com/mapnik/python-mapnik/blob/master/test/python_tests/utilities.py#L85-L95 (but you could also just use the more fancy `mapnik.blend` API)
  - Currently the Mapnik SVG parser does not always throw but rather prints to stderr in many cases (see `MAPNIK_LOG_ERROR` in https://github.com/mapnik/mapnik/blob/master/src/svg/svg_parser.cpp. This will need to be fixed for this API to know if an SVG fails to parse (and mapnik core can adjust easily I think)
  - Because the SVG rasterization code has only been an internal API so far, its not super friendly. I once made an attempt to refactor the code in https://github.com/mapnik/mapnik/compare/marker-refactor, but this never landed and is way out of date. But in general this would be valuable: light refactoring in Mapnik core so that `src/marker_cache.cpp`, `util/svg2png/svg2png.cpp` and this future API all can share a bit more code where appropriate.

**Comment by springmeyer** [comment]
> start coding a prototype and see how it feels

Just spoke with @danpat - he's taking a first pass at this.

**Comment by flippmoke** [comment]
What about if instead we just exposed it all in `Image.open` and `Image.fromBytes` rather then a custom `fromSVG`?  I feel more comfortable doing that as we already deal with image parsing options, etc. I would rather see this as repeatable code so it could simply be an image file open option, then it would work in python bindings and core as well?

**Comment by danpat** [comment]
`Image::open` would be pretty straightforward, there is already file-type detection going on there in `node-mapnik`, we could just look for `.svg`.

`Image::fromBytes` would require updates to `mapnik/src/image_reader.cpp`, as the magic number detection is occurring inside `mapnik` proper.

@tmcw: how are you most likely to feed the SVG data in?  From a filesystem path, or from an in-memory buffer?

**Comment by tmcw** [comment]
> @tmcw: how are you most likely to feed the SVG data in? From a filesystem path, or from an in-memory buffer?

Most likely via a buffer: it's likely that we'll store raw sprite data on DynamoDB.

**Comment by flippmoke** [comment]
I think we should support both @danpat if we are going to support it as an image reading type.

We already have a vague usage of SVG as an image type (even though its geometry). 
https://github.com/mapnik/mapnik/blob/master/include/mapnik/image_util.hpp#L380

I would think it might be best if we treated it similar to other image types for reading, but this would take thoughtful consideration and time in mapnik core (we might also think about Image.save for svg, but not sold on that). For example reading like: https://github.com/mapnik/mapnik/blob/master/src/png_reader.cpp

**Comment by danpat** [comment]
@tmcw - The branch https://github.com/mapnik/mapnik/tree/svg-rasterizer has the necessary changes to support loading SVG images via `Image::open` and `Image::fromBytes`, auto-detecting SVG content.  No changes to `node-mapnik` are needed.

Currently no parameters are available, the returned image is of whatever size the SVG specifies in the `width` and `height` attributes on the `<svg>` tag.  There's currently no good way to pass any extra parameters through to the backend, if that's required (for scaling, etc), I'll need some advice on the best approach.

**Comment by tmcw** [comment]
@samanpwbb what's the deal with svg sizing? do people declare the retina size in their SVG files, or the 1x size?

**Comment by samanpwbb** [comment]
Should be fine to assume svgs are 1x always.

**Comment by tmcw** [comment]
Okay, so @danpat 

>  There's currently no good way to pass any extra parameters through to the backend, if that's required (for scaling, etc), I'll need some advice on the best approach.

To support 2x and potentially 3x sprites, we'll need to pass through a 'scale' parameter

**Comment by danpat** [comment]
I've added `fromSVGSync` and `fromSVGBytesSync` to the node-mapnik/svg-rasterizer2 branch.

To use, you'll also need mapnik-latest, there were some symbols that weren't exported that were required.

Example usage:

       var svgdata = "<svg width='100' height='100'><g id='a'><ellipse fill='#FFFFFF' stroke='#000000' stroke-width='4' cx='50' cy='50' rx='25' ry='25'/></g></svg>";
       var buffer = new Buffer(svgdata, 'binary');
       var img = new mapnik.Image.fromSVGBytesSync(buffer, {scale: 0.5});

**Comment by springmeyer** [comment]
@danpat - great work. As far as getting easy-to-test binaries published, let's pick this up next week. Travis is experiencing some of the slowest response times I've seen (your build from last night is still in the queue!). But when you do try publishing again, pull in https://github.com/mapnik/node-mapnik/commit/87e3248aae6cd9bb1fd2c04b72ed25d70b49f006 which should get you mapnik core binaries with the symbols you need visible.

**Comment by tmcw** [comment]
:+1: excited for binaries!

**Comment by springmeyer** [comment]
kicked off binary builds - details at https://github.com/mapnik/node-mapnik/pull/469. These should be ready for testing by @tmcw in ~ 20 minutes.

**Comment by springmeyer** [comment]
Closing, will track remaining work that needs to be done before this lands at https://github.com/mapnik/node-mapnik/pull/469
