### ISSUE TITLE
No remove_layer in mapnik-node

### ISSUE THREAD

**Issue by BHare1985** [mapnik/node-mapnik#467]
Is it possible to add remove_layer or have some sort of way to modify a layer dynamically via node?

The only functions I see are 

```
    // layer access
    NODE_SET_PROTOTYPE_METHOD(lcons, "add_layer", add_layer);
    NODE_SET_PROTOTYPE_METHOD(lcons, "get_layer", get_layer);
    NODE_SET_PROTOTYPE_METHOD(lcons, "layers", layers);
```
ref: https://github.com/mapnik/node-mapnik/blob/master/src/mapnik_map.cpp

But in mapnik we have https://github.com/mapnik/mapnik/blob/master/src/map.cpp#L334

**Comment by springmeyer** [comment]
This omission was intentional: standard practice is to consider instances of a mapnik.Map as immutable. So you create them once / load an XML and after that you don't modify them. This makes async code predictably safe.

If you are writing an app that creates layers one by one and exposes an interface to modify them in place (sounds like you are) then I recommend using your own structure to hold layers + styles and then creating a new mapnik.Map and adding them lazily when you need to render.

If you think the above is not feasible, happy to discuss more. However that is a pretty reliable and simple approach that I would recommend. Loading maps from XML might sound "slow" but its actually been heavily optimized for this kind of case.

**Comment by BHare1985** [comment]
I understand the practice, and will approach it differently.

**Comment by zdila** [comment]
@springmeyer Isn't `add_layer` also mutating `mapnik.Map`?

I would also find `remove_layer` useful - in my case I'd like to clone a `mapnik.Map` (from a pool), remove some optional layers, render it and throw the clone away.

**Comment by zdila** [comment]
@springmeyer how to find a reviewer?
