### ISSUE TITLE
Appveyor tests failing from missing pbf reader

### ISSUE THREAD

**Issue by jakepruitt** [mapnik/node-mapnik#543]
When trying a new version of mapnik-vector-tile related to the geometry test suite, a fatal error on appveyor appeared indicating a missing `protozero/pbf_reader.hpp` file:

```
c:\projects\node-mapnik\node_modules\mapnik-vector-tile\src\vector_tile_geometry_decoder.hpp(10): fatal error C1083: Cannot open include file: 'protozero/pbf_reader.hpp': No such file or directory (compiling source file ..\src\mapnik_vector_tile.cpp) [C:\projects\node-mapnik\build\mapnik.vcxproj]
gypnode-pre-gypFailed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\projects\node-mapnik\lib\binding\node-v11-win32-x64\mapnik.node --module_name=mapnik --module_path=C:\projects\node-mapnik\lib\binding\node-v11-win32-x64' (1)
```

Here is the link for the failing build:
https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.873/job/so9u0spmnt8a5yl6#L1251

**Comment by springmeyer** [comment]
@jakepruitt - took a closer look. I think what must have happened is that you branched off your local master but it was out of date? I'm thinking this is what happened because I tried merging master into your branch and saw a lot of new stuff come in. So I rebranched off latest master and kicked off this built against latest mapnik-vt (now that you've merged your work) and we're all green: https://ci.appveyor.com/project/Mapbox/node-mapnik. \o/. Now of course what we really should be doing is running the mapnik-vt tests on windows too - let's track that at https://github.com/mapbox/mapnik-vector-tile/issues/159
