### ISSUE TITLE
Persist underlying buffer for mapnik.Image.fromBufferSync

### ISSUE THREAD

**Issue by mikemorris** [mapnik/node-mapnik#580]
Let's add a `Nan::Persistent` ref to preserve the underlying pixel data buffer when creating an image with `mapnik.Image.fromBufferSync`. This would keep this method zero-copy while minimizing the dependency on the lifetime of an external object and allow us to [remove the current scary warning recommending to not use this method](https://github.com/mapnik/node-mapnik/blob/03b3eb086eed36f68d483201db905a15f8a2f058/src/mapnik_image.cpp#L2782-L2783).

I'm not too familiar with the low level bits here, but from reading a little it sounds like we can't `std::move` the underlying `char*` from the buffer. It looks like node-osmium achieves similar functionality here by [wrapping the buffer, then moving the wrapper](https://github.com/osmcode/node-osmium/blob/93480131a1458c5cda44c0a6a8886f8cd3ee5687/src/buffer_wrap.cpp#L47)? I suppose an implementation like this could be an alternative to keeping an external buffer alive.

**Comment by springmeyer** [comment]
@mikemorris - I think the best approach is to dynamically stick the buffer onto the image object. Using `Nan::Persistent` is not going to work well because that, being a static type, would require all `mapnik.Image` objects to have an extra member of `Nan::Persistent`. Which is unnecessary bloat.

So, I've implemented that sticking hack in e9bd36e. It is basically the same thing as doing in JS:

```js
var im = new mapnik.Image.fromBufferSync(im.width(), im.height(), data);
im.data = data;
```

But implemented in C++. Can you test to ensure this branch `persist-buffer` is able to completely prevent the problem you were seeing?

**Comment by springmeyer** [comment]
@mikemorris - any progress on testing this? Does it work? If so, then the next step is to try @jfirebaugh's cleaner method https://github.com/mapnik/node-mapnik/commit/e9bd36e44880c8ce9320b67e058032023e7775e3#commitcomment-15658331 and go with that if it also works.

**Comment by mikemorris** [comment]
I currently have https://github.com/mapbox/api-gl/commit/b5e525274224920965abd78b7ac4fb6136400c66 deployed to staging and I'm not able to reproduce the lost data issue - want to take a look to confirm @miccolis?

**Comment by mikemorris** [comment]
Tested this over the past two days, and it looks like both the original patch and @jfirebaugh's suggest fix will work.

**Comment by springmeyer** [comment]
Testing script to confirm that the patch for this is working:

```js

var weak = require('weak');
var assert = require('assert');
var mapnik = require('./lib');
var vm = require('vm');

/*

Run this script like:

$ node --expose_gc persist.js 

The idea is that `im` will get garbage collected and because `data` is copied
and a reference is held to it by `mapnik.Image.fromBufferSync` it will stay safe
to use via im2 calls.

*/


var im = new mapnik.Image.open('test/data/images/sat_image.png');
var image_cleaned_up = false;

var ref1 = weak(im, function () {
  image_cleaned_up = true;
})

var data = im.data();
var data_cleaned_up = false;

var ref2 = weak(data, function () {
  data_cleaned_up = true;
})

var im2 = new mapnik.Image.fromBufferSync(im.width(), im.height(), data);

setTimeout(function() {
    // force garbage collection
    gc();
    // call im2 in order to keep it in scope
    assert(im2.getPixel(0,0) == 4287134743);
    assert(image_cleaned_up);
    assert(!data_cleaned_up);
    console.log('success!');    
},500)
```

Two options to solve this are referenced above:

  - My hack of adding, dynamically, a private variable of `_buffer` to the image object in order to ask V8 to keep the `_buffer` around.
  - @mikemorris's approach of using `SetInternalFieldCount(2)` to ask v8 to create space at the time of `mapnik.Image` creation for another ref to a C++ object and then setting that field to keep the buffer alive.

I prefer my hack because creating a dedicated slot/space is overkill. That means that unneeded space will be allocated for every `mapnik.Image` object ever created. Whereas in this case we'd only use that space when `mapnik.Image.fromBufferSync` is called. ThereforeI think my solution is more in line with intent (only keep a buffer around in the case of `mapnik.Image.fromBufferSync` usage) and will likely use less memory.
