### ISSUE TITLE
Is it possible to stream data to VectorTile.addGeoJSON? 

### ISSUE THREAD

**Issue by hampelm** [mapnik/node-mapnik#657]
Is it possible to [stream geojson](http://stackoverflow.com/questions/37735247/is-it-possible-to-stream-data-to-a-vectortiles-layer-using-node-mapnik) to a vector tile layer? (It'd be helpful for us in keeping memory use & processing down)

My read from testing and an uneducated look at the code is that it's not currently possible. It appears that VectorTile.addGeoJSON behaves like setGeoJSON (that is, it replaces the specified layer with the new geojson string.)

**Comment by flippmoke** [comment]
@hampelm sorry for way late response but your issue comes down to the fact vector tiles can not have two layers with the same name. Therefore, it is rejected when you attempt to add another layer name `'my-layer'`. Use a different layer name each time perhaps, or collect all your geojson to a feature collection prior and then execute all at once on a layer.

```
stream.on('data', function(data) {
  vt.addGeoJSON(JSON.stringify(data.feature), 'my-layer');
});
```
http://mapnik.org/documentation/node-mapnik/3.5/#VectorTile.addGeoJSON
