### ISSUE TITLE
Expose a means of converting Geometry type integers to strings

### ISSUE THREAD

**Issue by davidtheclark** [mapnik/node-mapnik#670]
The method http://mapnik.org/node-mapnik/documentation/3.5/#Geometry.type seems to be returning an integer, 0-7, which I then have to convert to a string: https://github.com/mapbox/mapbox-geostats/blob/master/lib/type-integer-to-string.js.

It would be nice if node-mapnik made this easier by either:

- exposing a conversion function,
- exposing an object mapping numbers to strings, or
- returning the string geometry name from `geometry.type`.

What do you think?

**Comment by springmeyer** [comment]
> seems to be returning an integer, 0-7, which I then have to convert to a string: https://github.com/mapbox/mapbox-geostats/blob/master/lib/type-integer-to-string.js.

Correct. By design it is an integer for fast comparison and small memory footprint. This way it can also be compared to the enumerations exposed on the `mapnik.Geometry` object like:

```js
if (features[0].geometry().type() == mapnik.Geometry.Polygon) { ... }
```

Thanks for your thoughts on making this easier and for taking the time to think about bringing it into node-mapnik to benefit everyone:

> exposing a conversion function

Conversion function could definitely be added to node-mapnik.

> exposing an object mapping numbers to strings

This is sort of already available:

```js
$ node -e "console.log(require('./lib/mapnik.js').Geometry)"
{ [Function: Geometry]
  Unknown: 0,
  Point: 1,
  MultiPoint: 4,
  LineString: 2,
  MultiLineString: 5,
  Polygon: 3,
  MultiPolygon: 6,
  GeometryCollection: 7 }
```

> returning the string geometry name from geometry.type.

As per above, Mapnik core treats this an an integer for best perf. This is also elegant so that we avoid any kind of assumptions about GeoJSON influencing core. However I'm comfortable with GeoJSON conventions being used in node-mapnik, so per above providing a conversion function sounds good.

This could be done right on the object like:

```diff
diff --git a/lib/mapnik.js b/lib/mapnik.js
index 96328fe..96d1197 100644
--- a/lib/mapnik.js
+++ b/lib/mapnik.js
@@ -86,6 +86,33 @@ if (process.env.MAPNIK_FONT_PATH) {
     });
 }
 
+function getGeometryType(mapnikType) {
+  switch (mapnikType) {
+    case mapnik.Geometry.Point:
+      return 'Point';
+    case mapnik.Geometry.LineString:
+      return 'LineString';
+    case mapnik.Geometry.Polygon:
+      return 'Polygon';
+    case mapnik.Geometry.MultiPoint:
+      return 'MultiPoint';
+    case mapnik.Geometry.MultiLineString:
+      return 'MultiLineString';
+    case mapnik.Geometry.MultiPolygon:
+      return 'MultiPolygon';
+    case mapnik.Geometry.GeometryCollection:
+      return 'GeometryCollection';
+    case mapnik.Geometry.Unknown:
+      return 'Unknown';
+    default:
+      return 'Unknown';
+  }
+}
+
+mapnik.Geometry.prototype.typeName = function() {
+    return getGeometryType(this.type());
+};
+
```

Let me know what you think would be best?

**Comment by davidtheclark** [comment]
@springmeyer Sorry I missed this comment for a while. Exposing a `geom.typeName()` conversion function sounds excellent to me!

**Comment by springmeyer** [comment]
@davidtheclark - okay, if the above patch works for you, then all we'd need to is tests to go with it to keep up at 100% coverage. Let me know if you are interested in getting that in node-mapnik via a PR and I'm happy to help. Or if you'd just like it done, that is okay too, let me know.

**Comment by davidtheclark** [comment]
@springmeyer Cool. I will try to help out with a PR soon and let you know if I flounder :)

**Comment by springmeyer** [comment]
👍 @davidtheclark
