### ISSUE TITLE
queryMapPoint documentation

### ISSUE THREAD

**Issue by Gilighost** [mapnik/node-mapnik#701]
Hi, I don't know where else to ask this. I am trying to use the queryMapPoint but cannot find any documentation for it, I looked in tests to see how it is used, but **I am wondering if the coordinates passed are from the bottom left of the image or top left**. Any help on queryMapPoint is appreciated.

**Comment by Gilighost** [comment]
queryMapPoint does not appear to be working. I looped through every pixel of the image and none returned any features.

**Comment by mapsam** [comment]
Hi @Gilighost could you please include some example code of how you are using `Mapnik.map.queryMapPoint()`?

You are right that this is not documented - my apologies. I'll start working through some docs.

**Comment by Gilighost** [comment]
Of course, I make a request to my server giving the i, j coordinates of where I clicked on the image. then use i and j like this. (mapReq has members i and j)

`function getFeatureInfo(mapReq, callback){
    createMap(mapReq, function(createMapError, map){
        //console.log(map);
        if(createMapError){
            callback(createMapError);
        }
        else{
            map.queryMapPoint(mapReq.i, mapReq.j, {layer: 0}, function(err, results) {
                if (err) throw err;
                callback(createMapError, results);
            });
        }
    });
}`

**Comment by Gilighost** [comment]
I'm sorry, let me try reformatting that

```function getFeatureInfo(mapReq, callback){
    createMap(mapReq, function(createMapError, map){
        if(createMapError){
            callback(createMapError);
        }
        else{
            map.queryMapPoint(mapReq.i, mapReq.j, {layer: 0}, function(err, results) {
                if (err) throw err;
                callback(createMapError, results);
            });
        }
    });
}```

**Comment by Gilighost** [comment]
I was having trouble with formatting, sorry. I make a request to my server passing the i, j coordinates of where I clicked the map image then I use queryMapPoint in the following function.
```javascript
function getFeatureInfo(mapReq, callback){
    createMap(mapReq, function(createMapError, map){
        if(createMapError){
            callback(createMapError);
        }
        else{
            map.queryMapPoint(mapReq.i, mapReq.j, {layer: 0}, function(err, results) {
                if (err) throw err;
                callback(createMapError, results);
            });
        }
    });
}```

**Comment by Gilighost** [comment]
`[{"layer":"railroads","featureset":{}}]` is always the return value

**Comment by mapsam** [comment]
@Gilighost that is an expected response (not obvious because of lack of documentation). The `{layer: 0}` can either be a string, such as `"railroads"` or a layer "index" such as `0` which you are using now.

The returned `results` is an array that contains objects which include a `layer` name (i.e. `railroads`) and a [`Featureset`](http://mapnik.org/documentation/node-mapnik/3.5/#Featureset) iterator. A `Featureset` is essentially an object that allows you to iterate across an infinite number of `Feature`s, which have their own methods documented here: http://mapnik.org/documentation/node-mapnik/3.5/#Feature

When working with a single `Feature` you can access attributes with `feature.attributes()` or geometry with `feature.geometry()`, for example. Depending on what information you're trying to retrieve you'll have to iterate through all `Feature`'s like this:

```javascript
map.queryMapPoint(mapReq.i, mapReq.j, {layer: 0}, function(err, results) {
  var fs = results[0].featureset; // assuming you're just grabbing the first object in the array
  var attributes = [];
  var feature;

  // grab all of the attributes and push to a temporary array
  while ((feature = fs.next())) {
    attributes.push(feature.attributes());
  }
  callback(null, attributes);
});
```

I'll start working on some documentation updates - thanks for opening this ticket!

**Comment by Gilighost** [comment]
@mapsam Thanks for the reply! That's just what I needed and helped me understand the featuresets better.
