### ISSUE TITLE
why is a custom version of clipper included in the node driver?

### ISSUE THREAD

**Issue by tjwebb** [mapnik/node-mapnik#725]
I can't figure out what changes have been made to clipper, compared to the actual version: https://github.com/skyrpex/clipper. The commits aren't very descriptive. Can someone summarize? Is there a reason the code is copy/pasted into this repo instead of loaded as a module?

**Comment by flippmoke** [comment]
@tjwebb the officially [angus clipper](http://www.angusj.com/delphi/clipper.php) library was the best approach we found initally for clipping polygons such that returned OGC valid results quickly in most situations. In order to make them more valid, we were making edits to the clipper library in the short term until such time as we found a viable solution. One of the edits we regularly make as well is having the angus clipper support mapnik geometry objects. Therefore, we had to manually edit it via a script after each update to the clipper library. 

This was an entirely large mess and it still wasn't making valid polygons in all situations. Therefore, I basically rewrote the majority of the angus clipper library and updated it to a new algorithm -- which is now called [wagyu](https://github.com/mapbox/wagyu). We are in the process of updating node-mapnik to use wagyu [right now](https://github.com/mapnik/node-mapnik/pull/719) and soon we will drop the dependence on the angus clipper all together.

**Comment by tjwebb** [comment]
ah, makes sense, thanks. pardon my ignorance: why is clipper included in the node-mapnik driver, and not just in the main mapnik project?

**Comment by flippmoke** [comment]
The more algorithms we can have outside mapnik core the better as they are more useful for use in other projects, mapnik itself is becoming more dependent on external header only libraries we are creating as well. Well tested, versioned independent libraries are a common thing we are doing at Mapbox so that more code can be shared.
