### ISSUE TITLE
Grayscale imageType not working in 3.5.14

### ISSUE THREAD

**Issue by mappagnosis** [mapnik/node-mapnik#737]
I am using Mapnik 3.5.14 on Ubuntu 16 via the Node bindings (node v 6).  I want to render a grayscale image (gray8) as per the [documentation](http://mapnik.org/documentation/node-mapnik/3.5/#mapnik.imageType).  However, the only image type that actually seems to work is rgba8.  All the others give the same message: `RENDER ERROR: Error: This image type is not currently supported for rendering.`  My code is as follows:

```
var im = new mapnik.Image(256, 256, {
	type: mapnik.imageType.gray8
});
```

These grayscale options have been available since 3.0 according to the change logs and I see unit tests for them, so I presume they are expected to work.  Is this a general bug, one specific to v3.5.14, or perhaps the Node bindings?

**Comment by flippmoke** [comment]
The grayscale rendering has not been fully implemented in Mapnik core - so this will not work properly for this currently. This has been discussed in the past as a something to implement in the entire mapnik pipeline but it has not because of some complexities associated with several different sections of the mapnik core code that would cause this to be a difficult task. 

I am closing this ticket because it is related to mapnik core and not to node-mapnik. /cc @artemp @lightmare
