### ISSUE TITLE
Strange logic 

### ISSUE THREAD

**Issue by artemp** [mapnik/node-mapnik#801]
https://github.com/mapnik/node-mapnik/blame/master/src/mapnik_vector_tile.cpp#L121 - why do we have this test ?

https://github.com/mapnik/node-mapnik/blame/master/src/mapnik_vector_tile.cpp#L153-L198 - what this method supposed to return for `Polygon` geometry ? 

/cc @springmeyer @flippmoke

**Comment by springmeyer** [comment]
> https://github.com/mapnik/node-mapnik/blame/master/src/mapnik_vector_tile.cpp#L121 - why do we have this test ?

I added that `if (num_points > 1)`. I think I did this because, based on the loop below, I could not imagine it working with a line with only 1 point. But I see now that the `for (std::size_t i = 1; i < num_points; ++i)` would work fine without this additional check. Is that also what you are seeing?

> https://github.com/mapnik/node-mapnik/blame/master/src/mapnik_vector_tile.cpp#L153-L198 - what this method supposed to return for Polygon geometry ?

Currently, as written, this is supposed to return a "hit" if a point falls within a polygon exterior ring and not within a interior ring. Ideally this would return a "hit" if a point falls within a polygon exterior ring or within a given distance to a polygon's exterior ring (if within a `tolerance` to one of the linear_ring segments). Currently, when the polygon has a hole, we consider it NOT a "hit" if the point falls within a hole. In retrospect, I regret adding this support as I don't think users of this API care about holes - they rather want to get back all polygons within a given distance of the search x,y, ignoring holes.

**Comment by springmeyer** [comment]
@artemp - also noticed just now the `hit_test` filter in mapnik core looks broken for polygons, per the FIXME: https://github.com/mapnik/mapnik/blob/master/include/mapnik/hit_test_filter.hpp#L92-L135

**Comment by springmeyer** [comment]
update: the code in node-mapnik does not propertly support polygon tolerance. Instead of fixing the node-mapnik code we've instead written a full replacement with additional features (https://github.com/mapbox/vtquery). Therefore this code path will be frozen and deprecated in future versions of node-mapnik: #842
