### ISSUE TITLE
tokens in Mapnik postgis sql sub-selects add quotes when replace with options.variables

### ISSUE THREAD

**Issue by steeeeps** [mapnik/node-mapnik#934]
Accordingly to documentation, mapnik.Map render method have options attribute that could contain variables object. So I  write sub-selects in  mapnik xml like this code :
```
<Parameter name="table">(SELECT geom1 FROM  table1 where  ST_Intersects ( geom1,!bbox! ) and year = !@year! ) as subquery </Parameter>
```
Then, I passed a integer value 'year' in variables ,  the map render code  :
```
map.render(tile, {
            variables: {
                "year": 2019
            }, (err, ti) => {
          ...
        });
```
But ,the problem is why mapnik add quotes arround !@year! in sql ,  the sql query log is  : 
```
SELECT ST_AsBinary(ST_Simplify(ST_SnapToGrid("geom1",30.5748), 61.1496)) AS geom FROM (SELECT geom1 FROM  table1 where  ST_Intersects ( geom1,ST_MakeEnvelope(13462700.91781152,5322463.153553393,13775786.9856676,5635549.221409475,3857) ) and year = '2019') as subquery
```
I expect year = !@year! should replaced with year = 2019 , but I always get year = '2019'.
thanks

**Comment by lightmare** [comment]
Good point.

So far, mapnik postgis plugin has first converted the variable value to string (losing original type information) and inserted that into query. In mapnik v3.0.x, the `value.to_string()` was inserted verbatim, so if you wanted to insert an actual string, you had to SQL-quote before passing it to mapnik, which was unwieldy (and also allowed injecting raw SQL, but that's beside the point).

In upcoming mapnik 4, I've changed variable interpolation so that the string is quoted. I've since hit this exact same issue, that an integer value gets converted to string and quoted, losing type information. And I began pondering whether we should preserve the original variable type (leaning to "hell yeah!"), already have the code in an experimental branch but not ready to be pushed yet.

Until our variable interpolation preserves the type, you can use explicit type casts in SQL, if automagic type coercion can't handle it:
```sql
-- these two should work whether the (integer) value is quoted or not
... year = cast(!@year! as integer) -- Standard SQL
... year = !@year!::int -- PostgreSQL

-- just don't use this PostgreSQL syntax, as it won't work when the value is not quoted
... year = int !@year! -- 
```

**Comment by steeeeps** [comment]
@lightmare Thank you very much, this answer solved my question。
